server:
  port: 9002
spring:
  application:
    name: feign-user-service
  datasource:
      url: jdbc:mysql://10.18.172.86:3306/myblog_user
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    UserService#test():
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 3
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500
#      circuitBreaker:
#        requestVolumeThreshold: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
