server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
spring:
  application:
    name: gateway-myblog
zuul:
  routes:
    api-user:
      path: /app-user/**
      serviceId: feign-user-service
    api-b:
      path: /app-sadfasefd/**
      serviceId: feign-consumer