server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
spring:
  application:
    name: user-service
  datasource:
#    url: jdbc:mysql://localhost:3306/myblog
    url: jdbc:mysql://10.18.172.86:3306/myblog_user
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
