server:
  port: 8998
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Starrrrk/myblog-config.git
          search-paths: gateway-myblog
#          search-paths: {application}
          username: ning15845920609@163.com
          password: ning1hong2bo3.
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: springcloud

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8900/eureka/
